# Generated by Django 4.2.7 on 2025-06-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='address',
            field=models.TextField(blank=True, help_text="Adresse complète de l'organisation", verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Description de votre organisation, vos activités et vos valeurs', verbose_name="Description de l'organisation"),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Photo de profil ou logo de l'organisation", null=True, upload_to='profiles/organizers/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de fois que le profil a été consulté', verbose_name='Vues du profil'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='website',
            field=models.URLField(blank=True, help_text="Site web de l'organisation (optionnel)", verbose_name='Site web'),
        ),
    ]
