# Generated by Django 4.2.7 on 2025-05-31 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('media_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='accounts.artistprofile', verbose_name='Artiste'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.artistprofile', verbose_name='Artiste'),
        ),
        migrations.AlterField(
            model_name='photofile',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_files', to='accounts.artistprofile', verbose_name='Artiste'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='accounts.artistprofile', verbose_name='Artiste'),
        ),
    ]
