# Generated by Django 4.2.7 on 2025-05-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0002_alter_audiofile_artist_alter_documentfile_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Taille du fichier en bytes', null=True, verbose_name='Taille du fichier'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Taille du fichier en bytes', null=True, verbose_name='Taille du fichier'),
        ),
        migrations.AlterField(
            model_name='photofile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Taille du fichier en bytes', null=True, verbose_name='Taille du fichier'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Taille du fichier en bytes', null=True, verbose_name='Taille du fichier'),
        ),
    ]
